language: python
python:
  - 3.5
  - 3.6
sudo: false
addons:
  postgresql: "9.4"
cache:
  directories:
    - ~/.cache/pip
matrix:
  include:
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=lint
install:
  - pip install tox-travis
script:
  - tox
notifications:
  slack:
    rooms:
      - readthedocs:y3hjODOi7EIz1JAbD1Zb41sz#random
    on_success: change
    on_failure: always
